name: Publish GitHub NPM Package

on:
  workflow_dispatch:

jobs:
  npm-publish:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@scottwestover"

      - run: git config user.email "scottwestover2006@gmail.com"
      - run: git config user.name "@github-ci"
      - run: npm version --patch --message "Bump version to %s"

      - run: git push
      - run: git push --follow-tags

      - name: npm publish
        run: npm publish
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
