name: Publish NPM Package

on:
  workflow_dispatch:

jobs:
  npm-publish:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}s

      # - run: git config user.email "scottwestover2006@gmail.com"
      # - run: git config user.name "@github-ci"
      # - run: yarn version --patch --message "Bump version to %s"

      # - run: git push
      # - run: git push --follow-tags

      # - name: publish
      #   run: |
      #     npm config set //registry.npmjs.org:_authToken ${NODE_AUTH_TOKEN}
      #     npm publish --access public --ignore-scripts
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}


      - name: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: "public"
