name: Publish NPM Package

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  npm-publish:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
          scope: "@devshareacademy"

      # - run: git config user.email "scottwestover2006@gmail.com"
      # - run: git config user.name "@github-ci"
      # - run: yarn version --patch --message "Bump version to %s"

      # - run: git push
      # - run: git push --follow-tags

      - name: publish
        run: |
          npm -v
          npm login
          npm publish --access public
          cat .npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}


      # - name: publish
      #   uses: JS-DevTools/npm-publish@v1
      #   with:
      #     token: ${{ secrets.NPM_TOKEN }}
      #     access: "public"
